### ISSUE TITLE
Pi3 app Issue

### ISSUE THREAD

**Issue by DEEKSHITHDP** [Taher1322/RPi-bluetooth_app#1]
Hi
I gone through this and it worked perfectly for me yesterday. But today again I run the python code and tried to connected with the pi3 Bluetooth manager app. In the terminal it is showing as connected, but in mobile phone after choosing raspberryPi address  next window is not opening to send the command. Please help
![IMG20201119155420](https://user-images.githubusercontent.com/70956082/99655724-10266980-2a82-11eb-81c0-fddd2a91acd0.jpg)
![Screenshot_2020-11-19-15-52-23-36_f6ff18be458d9dbd2ab8389f003e6b11](https://user-images.githubusercontent.com/70956082/99655529-da818080-2a81-11eb-99e1-fb281c678d7f.png)

**Comment by Taher1322** [comment]
Try restarting the app. Sometimes it shows connected but then data transmission doesn't happen, but that can be resolved by restarting the app and reinitializing the connection of Bluetooth again by running the dataread.py file. 
Check this out

**Comment by DEEKSHITHDP** [comment]
Tried it but still same issue

**Comment by Taher1322** [comment]
Which app restating you did? Not the dataread.py. I am talking about the Android app. Remove it from background running and then try it. Maybe that may help.

**Comment by DEEKSHITHDP** [comment]
> Which app restating you did? Not the dataread.py. I am talking about the Android app. Remove it from background running and then try it. Maybe that may help.

I restarted android app only. Now again uninstalled and re-installed again, again cloned to git after deleting previous one. Still the same Issue. Please help.

**Comment by DEEKSHITHDP** [comment]
I used Serial Bluetooth Terminal app for the same code with some modification in the app(You have to go to settings, give new line option to null).It works greatly.
